services:
  - type: web
    name: dripline-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_KEY
        sync: false
      - key: SUCCESS_URL
        sync: false
      - key: CANCEL_URL
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_ENV
        value: sandbox
      - key: SMS_EMAIL_SERVICE
        value: gmail
      - key: SMS_EMAIL_USER
        sync: false
      - key: SMS_EMAIL_PASS
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: PORT
        value: 4000
